/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_banhngot;

/**
 *
 * @author ASUS
 */
public class home extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        text();
    }
    public void text()
    {
        frmDangNhap dn = new frmDangNhap();
        int quyen = dn.quyen();
        if(quyen == 1)
        {           
            lbtext.setText("CHÀO MỪNG QUẢN LÝ");
        }
        if(quyen == 2)
        {
            lbtext.setText("CHÀO MỪNG NHÂN VIÊN");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtext = new javax.swing.JLabel();

        lbtext.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbtext.setForeground(new java.awt.Color(51, 51, 255));
        lbtext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtext.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\DA_JAVA\\JAVA_BANH_NGOT\\QL_BanhNgot\\images\\user-64.png")); // NOI18N
        lbtext.setText("CHÀO MỪNG");
        lbtext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbtext.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtext, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtext, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbtext;
    // End of variables declaration//GEN-END:variables
}
