/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_banhngot;

import Controller.TruyVan;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import Model.NhanVien;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public final class JINhanVien extends javax.swing.JInternalFrame {
    private final NhanVien nhanvien = new NhanVien();  
    private boolean cothem=true; 
    private final DefaultTableModel tableModel = new DefaultTableModel(); 
    ResultSet rs = null;
    TruyVan sql;
    /**
     * Creates new form JINhanVien
     */
        
    /*public void LoadNV()
    {
        rs=sql.NhanVien();
        Vector item=null;
        String kt[]={"So","Hoten","SDT","Nam sinh"};
        DefaultTableModel tableModel = new DefaultTableModel(kt,0);
        tableModel.setRowCount(0);
        try
        {
            while(rs.next())
            {
               
                item = new Vector();
                item.add(rs.getInt("MaNV")); 
                item.add(rs.getString("TenNV"));
                item.add(rs.getString("SDT"));
                item.add(rs.getDate("NamSinh"));   
                  
                
              tableModel.addRow(item);                
            }
            JTableNhanVien.setModel(tableModel);
        } catch (SQLException ex)
        {
            System.out.println(ex.toString());
        }
    }*/
    public void ClearData(){
        int n = tableModel.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tableModel.removeRow(i);
        }
    }
    public void ShowData() throws SQLException{         
        ResultSet result=  nhanvien.ShowNhanVien();           
        try {             
            while(result.next()){
                String rows[] = new String[4]; 
                rows[0] = result.getString(1); 
                rows[1] = result.getString(2);
                rows[2] = result.getString(3); 
                rows[3] = result.getString(4);
                tableModel.addRow(rows);    
            } 
        }  
       catch (SQLException e) {
           JOptionPane.showMessageDialog(this, "Dữ liệu trống","Thông báo",JOptionPane.OK_OPTION);
        }  
    }
    private void setNull(){
        this.txt_MaNV.setText(null);
        this.txt_TenNV.setText(null);
        this.txt_SDT.setText(null);
        this.txt_Namsinh.setText(null);
        this.txt_MaNV.requestFocus();
    }
    
    private void setKhoa(boolean a){
        this.txt_MaNV.setEnabled(!a);
        this.txt_TenNV.setEnabled(!a);
        this.txt_SDT.setEnabled(!a);
        this.txt_Namsinh.setEnabled(!a);
    }
    
    private void setButton(boolean a){
        this.btn_Them.setEnabled(a);
        this.btn_Xoa.setEnabled(a);
        this.btn_Sua.setEnabled(a);
        this.btn_Luu.setEnabled(!a);
        this.btn_Huy.setEnabled(!a);
    }
    public JINhanVien() throws SQLException {
        initComponents();
        //sql = new TruyVan();
        String []colsName = {"Mã NV", "Tên NV", "SĐT", "Năm sinh"};
        tableModel.setColumnIdentifiers(colsName);
        JTableNhanVien.setModel(tableModel);
        ShowData();
        setNull();
        setKhoa(true);
        setButton(true);
        //this.btn_Tim.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        txt_TenNV = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_Namsinh = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Tim = new javax.swing.JButton();
        lb_hoten = new javax.swing.JLabel();
        lb_sdt = new javax.swing.JLabel();
        lb_namsinh = new javax.swing.JLabel();
        lb_timkiem = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_Luu = new javax.swing.JButton();
        btn_Huy = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableNhanVien = new javax.swing.JTable();

        setTitle("NHÂN VIÊN");

        tittle.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        tittle.setText("DANH SÁCH NHÂN VIÊN");
        tittle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittle)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_Them.setText("Thêm");
        btn_Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMouseClicked(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SuaMouseClicked(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaMouseClicked(evt);
            }
        });

        btn_Tim.setText("Tìm");
        btn_Tim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimMouseClicked(evt);
            }
        });

        lb_hoten.setText("Họ và tên:");

        lb_sdt.setText("Số điện thoại:");

        lb_namsinh.setText("Năm sinh:");

        lb_timkiem.setText("Tìm kiếm");

        jLabel1.setText("Mã Nhân viên:");

        btn_Luu.setText("Lưu");
        btn_Luu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LuuMouseClicked(evt);
            }
        });

        btn_Huy.setText("Hủy");
        btn_Huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HuyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_sdt)
                                    .addComponent(lb_hoten)
                                    .addComponent(lb_namsinh))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btn_Them)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(192, 192, 192)
                                    .addComponent(btn_Tim))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txt_Namsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lb_timkiem)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_MaNV, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_TenNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Luu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Huy)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hoten))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_sdt)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_namsinh)
                    .addComponent(lb_timkiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Namsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them)
                    .addComponent(btn_Sua)
                    .addComponent(btn_Xoa)
                    .addComponent(btn_Tim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Luu)
                    .addComponent(btn_Huy)))
        );

        JTableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MaNV", "TenNV", "SDT", "Namsinh"
            }
        ));
        JTableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableNhanVien);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableNhanVienMouseClicked
        // TODO add your handling code here:
            try{ 
            //Lay chi so dong dang chon 
            int row =this.JTableNhanVien.getSelectedRow(); 
            String nv=(this.JTableNhanVien.getModel().getValueAt(row,0)).toString(); 
            ResultSet rs= nhanvien.ShowNhanVienTheoMa(nv); 
            if(rs.next())//Neu co du lieu 
            { 
             this.txt_MaNV.setText(rs.getString("MaNV")); 
             this.txt_TenNV.setText(rs.getString("TenNV"));
             this.txt_SDT.setText(rs.getString("SDT"));
             this.txt_Namsinh.setText(rs.getString("Namsinh"));
            } 
        } 
     catch (SQLException e) { 
        }                                                             
    }//GEN-LAST:event_JTableNhanVienMouseClicked

    private void btn_XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaMouseClicked
        // TODO add your handling code here:
        String manv = txt_MaNV.getText();
        try{
            if(manv.length() == 0){
                JOptionPane.showMessageDialog(null,"Chọn một nhân viên để xóa","Thông báo",1);
            }
            else{
                if(JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa nhân viên mã "+manv+" này hay không?","Thông báo",2 ) == 0){
                    nhanvien.XoaNhanVien(manv);
                    ClearData();
                    ShowData();
                    setNull();
                }
            }
        }
        catch(SQLException e){
            Logger.getLogger(JISanPham.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_XoaMouseClicked

    private void btn_ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMouseClicked
        // TODO add your handling code here:
        setNull();
        setKhoa(false);
        this.txt_MaNV.setEnabled(false);
        txt_MaNV.setText(null);
        setButton(false);
        //this.txt_TenNV.setEnabled(false);
        cothem = true;
    }//GEN-LAST:event_btn_ThemMouseClicked

    private void btn_SuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SuaMouseClicked
        // TODO add your handling code here:
        String ma = txt_MaNV.getText();
        if(ma.length() == 0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhân viên cần chỉnh sửa","Thông báo",1);
        }
        else{
            setKhoa(false);
            this.txt_MaNV.setEnabled(false);
            setButton(false);
            cothem = false;
        }
    }//GEN-LAST:event_btn_SuaMouseClicked

    private void btn_LuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LuuMouseClicked
        // TODO add your handling code here:
        String ma=txt_MaNV.getText();
        String ten = txt_TenNV.getText();
        String sdt=txt_SDT.getText();
        String ns = txt_Namsinh.getText();
        if(ten.length() == 0){
            JOptionPane.showMessageDialog(null,"Vui lòng đừng bỏ trống thông tin","Thông báo", 1);
        }
        else{
                try{
                    if(cothem){
                        nhanvien.ThemNhanVien(ten, sdt, ns);
                    }
                    else{
                        nhanvien.SuaNhanVien(ma, ten, sdt, ns);
                    }
                    ClearData();
                    ShowData();
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "Cập nhật thất bại","Thông báo",1);
                }
                setNull();
                setKhoa(true);
                setButton(true);
            }
    }//GEN-LAST:event_btn_LuuMouseClicked

    private void btn_HuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HuyMouseClicked
        // TODO add your handling code here:
        setNull();
        setKhoa(true);
        setButton(true);
    }//GEN-LAST:event_btn_HuyMouseClicked

    private void btn_TimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimMouseClicked
        // TODO add your handling code here:
        String tennv = this.txtTimKiem.getText();
        if(tennv.length() == 0){
            JOptionPane.showMessageDialog(null,"Vui lòng nhập tên nhân viên","Thông báo", 1);
        }
        else{
            try{
                ResultSet result = nhanvien.ShowNhanVienTheoTen(tennv);
                System.out.println(result.wasNull());
                ClearData();
                while(result.next()){
                String rows[] = new String[4]; 
                rows[0] = result.getString(1); 
                rows[1] = result.getString(2);
                rows[2] = result.getString(3); 
                rows[3] = result.getString(4);
                tableModel.addRow(rows);
                }
            }
            catch(SQLException e){
                Logger.getLogger(JINhanVien.class.getName()).log(Level.SEVERE,null,e);
            }
            
        }
    }//GEN-LAST:event_btn_TimMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableNhanVien;
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Tim;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_hoten;
    private javax.swing.JLabel lb_namsinh;
    private javax.swing.JLabel lb_sdt;
    private javax.swing.JLabel lb_timkiem;
    private javax.swing.JLabel tittle;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_Namsinh;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNV;
    // End of variables declaration//GEN-END:variables
}
